### PR TITLE
fix: rename  module math to start with uppercase character

### PR DESCRIPTION
**Pull request by yazaldefilimone**

### CODE REVIEW

**Comment by imteekay** [comment]
Thanks for the contribution, but apparently, `readFileSync` is case insensitive, so the naming doesn't really matter that much. I tested with `Math` and `math` and both works well.

**Comment by imteekay** [comment]
Thanks for the contribution, but apparently, `readFileSync` is case insensitive, so the naming doesn't really matter that much. I tested with `Math` and `math` and both work well.

**Comment by yazaldefilimonepinto** [comment]
> Thanks for the contribution, but apparently, `readFileSync` is case insensitive, so the naming doesn't really matter that much. I tested with `Math` and `math` and both work well.

Interesting, because when I tried to run the test on my machine, an error occurred. I'm using Ubuntu 22.04.3 and Node.js version 18.13.0. Is a specific Node.js version?

Screenshot from 2023-10-14 14-59-28

Screenshot from 2023-10-14 14-59-37

**Comment by imteekay** [comment]
Yeah, I tested it out with running in Linux on CI and it gets the same error ([build](https://github.com/imteekay/essentials-of-interpretation/actions/runs/6517921451/job/17702834484?pr=2)).

I implemented the ci and it's already in master, can you please rebase your branch with master so we make sure this fixes the error?

**Comment by yazaldefilimonepinto** [comment]
I'm not sure if this is necessary, but I added the `_resolveModule` function that attempts to make module loading case-insensitive.

**Comment by imteekay** [comment]
For some reason, this PR is not triggering the CI build. I merged another PR https://github.com/imteekay/essentials-of-interpretation/pull/3 to trigger builds for pull requests. Let's see if it triggers the build now.

> I'm not sure if this is necessary, but I added the _resolveModule function that attempts to make module loading case-insensitive.

I think this is not really necessary. You can stick with just the file renaming.

**Pull request merged**
